# Generated by Django 5.2.1 on 2025-05-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='price',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='language',
        ),
        migrations.AddField(
            model_name='tarif',
            name='acte',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarif',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
