# Generated by Django 5.2.1 on 2025-05-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0002_rename_price_tarif_prix_remove_tarif_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarif',
            old_name='prix',
            new_name='price',
        ),
    ]
