# Generated by Django 5.2.1 on 2025-05-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('question', 'Question posée'), ('feedback', 'Feedback soumis'), ('admin_action', 'Action admin'), ('login', 'Connexion'), ('logout', 'Déconnexion')], max_length=255)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
