# Generated by Django 5.2.1 on 2025-05-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_log_remove_role_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
